# core/vault.jl — Vault struct と constructor

"""
    Vault

Handle for a single (study, run) pair.
Wraps a `ConfigSpec` and resolves file paths under `outdir`.

# Fields

- `config_path`: absolute path to the source config TOML
- `spec`:        parsed `ParamIO.ConfigSpec` (study, path_keys, paramsets)
- `outdir`:      absolute root path under which `data/`, `status/`, `bin/`,
                 `figure/`, and `.datavault/` live
- `run`:         named campaign / phase within the study. Defaults to
                 `"default"`. Use distinct names to keep multi-phase
                 explorations separate (e.g. `"phase1"`, `"phase2_refined"`)
- `path_formatter`: function `(DataKey, path_keys) -> String`

# outdir resolution

Priority: constructor argument > `ENV["DATAVAULT_OUTDIR"]` > config value.

# Multi-run usage

A study (= one `project_name`) may contain multiple runs. Each run gets its
own data / status / bin / figure subtree under `{outdir}/{layer}/{project}/{run}/`
and its own discovery anchor at `{outdir}/.datavault/{project}/{run}.log.toml`.

```julia
v1 = Vault("configs/linear_response.toml"; run="phase1",         outdir="out/")
v2 = Vault("configs/linear_response.toml"; run="phase2_refined", outdir="out/")
```

Multiple parallel jobs can share the same `(project, run)`: each job touches
different `DataKey`s, and the log.toml upsert is idempotent and atomic.

# Custom path naming

By default, paths are generated by `ParamIO.format_path`. Pass a custom
function via `path_formatter` if needed:

    formatter(key::DataKey, path_keys::Vector{String}) -> String

Note: a custom formatter cannot be reproduced from log.toml alone, so
DataVault will warn at construction time.
"""
struct Vault
    config_path::String
    spec::ParamIO.ConfigSpec
    outdir::String
    run::String
    path_formatter::Function
end

function Vault(
    config_path::AbstractString;
    run::AbstractString="default",
    outdir::Union{AbstractString,Nothing}=nothing,
    path_formatter::Function=ParamIO.format_path,
)
    spec = ParamIO.load(config_path)

    resolved = if outdir !== nothing
        string(outdir)
    elseif haskey(ENV, "DATAVAULT_OUTDIR")
        ENV["DATAVAULT_OUTDIR"]
    else
        spec.study.outdir
    end

    vault = Vault(
        abspath(config_path), spec, abspath(resolved), string(run), path_formatter
    )

    # log.toml upsert is the discovery anchor and validates path_keys against
    # any pre-existing entry — must run first so a conflicting run name fails
    # before we touch the data subtree.
    _save_log_toml(vault)
    _save_config_snapshot(vault)
    vault
end
