# core/vault.jl — Vault struct と constructor

"""
    Vault

Handle for a single computation study.
Wraps a `ConfigSpec` and resolves file paths under `outdir`.

Priority for `outdir`: constructor argument > `ENV["DATAVAULT_OUTDIR"]` > config value.

# Custom path naming

By default, paths are generated by `ParamIO.format_path(key, path_keys)`
(e.g. `"N24_chi40_g0.50_h0.00"`).

If your project needs a different naming convention (e.g. to keep
backward-compatibility with legacy data), pass a custom function via
`path_formatter`. The function must have the signature:

    formatter(key::DataKey, path_keys::Vector{String}) -> String

Example:
```julia
my_format = (key, _) -> "N\$(key.params["system.N"])_chi\$(key.params["system.chi"])"
vault = Vault("configs/study.toml"; path_formatter=my_format)
```
"""
struct Vault
    config_path::String
    spec::ParamIO.ConfigSpec
    outdir::String
    path_formatter::Function
end

function Vault(
    config_path::AbstractString;
    outdir::Union{AbstractString,Nothing}=nothing,
    path_formatter::Function=ParamIO.format_path,
)
    spec = ParamIO.load(config_path)

    resolved = if outdir !== nothing
        string(outdir)
    elseif haskey(ENV, "DATAVAULT_OUTDIR")
        ENV["DATAVAULT_OUTDIR"]
    else
        spec.study.outdir
    end

    vault = Vault(abspath(config_path), spec, abspath(resolved), path_formatter)
    _save_config_snapshot(vault)
    vault
end
